import type { EquitySource, ExposureNetwork } from "./debtrank";
import countryList from "../data/network_snapshot.json";
import borders from "../data/world_borders.json";

export interface CountryNode {
  id: string;
  name: string;
  lat: number;
  lng: number;
}

interface RawCountryList {
  nodes: { id: string; name: string; lat: number | null; lng: number | null }[];
}

// id/name/lat/lng never change across years, so this stays a static bundled
// import; the per-year financials and exposure edges are fetched on demand
// via loadYearData below (see YEARS / the historical scrubber in App.tsx).
export const countries: CountryNode[] = (countryList as RawCountryList).nodes
  .filter((n) => n.lat !== null && n.lng !== null)
  .map((n) => ({ id: n.id, name: n.name, lat: n.lat as number, lng: n.lng as number }));

export const YEARS = Array.from({ length: 21 }, (_, i) => 2005 + i);
export const DEFAULT_YEAR = YEARS[YEARS.length - 1];

export interface ExposureEdge {
  creditor: string;
  debtor: string;
  amount: number;
}

interface YearNode {
  id: string;
  gdp_usd: number | null;
  reserves_usd: number | null;
  external_debt_usd: number | null;
  bank_capital_ratio_pct: number | null;
}

export interface YearSnapshot {
  nodes: YearNode[];
  edges: ExposureEdge[];
}

const yearCache = new Map<number, YearSnapshot>();

/** Fetches (and caches) the network snapshot for a given year, generated by
 * data-pipeline/build_snapshot.py --by-year and served statically from
 * public/data/network/{year}.json. */
export async function loadYearData(year: number): Promise<YearSnapshot> {
  const cached = yearCache.get(year);
  if (cached) return cached;
  const dataUrl = `${import.meta.env.BASE_URL}data/network/${year}.json`;
  const res = await fetch(dataUrl);
  if (!res.ok) throw new Error(`Failed to load network data for ${year}`);
  const data = (await res.json()) as YearSnapshot;
  yearCache.set(year, data);
  return data;
}

// Same fallback chain as model/debtrank_model/cli.py: reserves are the
// natural sovereign loss-absorbing buffer, falling back to a slice of GDP,
// then a floor tied to the node's own cross-border banking footprint, so
// every node has strictly positive equity.
//
// The footprint floor exists because reserves/GDP are meaningless proxies for
// cross-border financial centres (Isle of Man, Cayman, BVI, Luxembourg, Hong
// Kong SAR, ...): BIS counts every bank *resident* there, so their reported
// claims/liabilities routinely run to multiples of local GDP, while several
// (e.g. Isle of Man) report no GDP or reserves to the World Bank at all and
// fell back to a flat $1e6 floor. Against tens of billions in real exposure
// that made exposure[i][j] / equity[i] saturate the impact matrix at 1 for
// nearly every edge, so those nodes hit full distress from almost any shock
// and dominated the propagation ranking regardless of which country was
// clicked.
//
// The floor's ratio is the country's own bank-capital-to-assets ratio
// (World Bank FB.BNK.CAPA.ZS, sourced from IMF Financial Soundness
// Indicators) applied to its gross cross-border footprint, when that's
// available -- real coverage runs from ~4% (e.g. Macao SAR, Japan) to ~10%
// (e.g. Ireland, Luxembourg), so a per-country figure is meaningfully more
// accurate than one flat assumption. Only the handful of jurisdictions with
// no World Bank data under *any* of these indicators (Isle of Man, Cayman,
// Bermuda, ...) fall back to the Basel III Pillar 1 minimum (8% of
// risk-weighted assets) as a last resort. Either way this never *lowers*
// equity below the old reserves/GDP estimate. See BIS Working Papers No.
// 1035 and BIS Quarterly Review, June 2022, "The outsize role of
// cross-border financial centres".
const DEFAULT_CAPITAL_RATIO = 0.08;

function equityFor(n: YearNode | undefined, grossFootprint: number): { value: number; source: EquitySource } {
  const reserves = n?.reserves_usd ?? 0;
  const gdpFallback = n?.gdp_usd ? n.gdp_usd * 0.01 : 0;
  const capitalRatio = n?.bank_capital_ratio_pct ? n.bank_capital_ratio_pct / 100 : DEFAULT_CAPITAL_RATIO;
  const footprintFloor = grossFootprint * capitalRatio;

  const candidates: [number, EquitySource][] = [
    [reserves, "reserves"],
    [gdpFallback, "gdp"],
    [footprintFloor, "capital_ratio"],
    [1e6, "floor"],
  ];
  let winner = candidates[0];
  for (const c of candidates) if (c[0] > winner[0]) winner = c;
  return { value: winner[0], source: winner[1] };
}

export function buildExposureNetwork(yearData: YearSnapshot): ExposureNetwork {
  const nodeIds = countries.map((c) => c.id);
  const index = new Map(nodeIds.map((id, i) => [id, i]));
  const byId = new Map(yearData.nodes.map((n) => [n.id, n]));

  const n = nodeIds.length;
  const exposure: number[][] = Array.from({ length: n }, () => new Array(n).fill(0));
  const grossFootprint = new Array(n).fill(0);
  for (const e of yearData.edges) {
    const i = index.get(e.creditor);
    const j = index.get(e.debtor);
    if (i === undefined || j === undefined) continue;
    exposure[i][j] += e.amount;
    grossFootprint[i] += e.amount;
    grossFootprint[j] += e.amount;
  }

  const resolved = nodeIds.map((id, i) => equityFor(byId.get(id), grossFootprint[i]));
  const equity = resolved.map((r) => r.value);
  const equitySource = resolved.map((r) => r.source);

  return { nodeIds, exposure, equity, equitySource };
}

/** Total in + out exposure for a country, used to size its marker. */
export function totalExposure(yearData: YearSnapshot, countryId: string): number {
  let total = 0;
  for (const e of yearData.edges) {
    if (e.creditor === countryId || e.debtor === countryId) total += e.amount;
  }
  return total;
}

const countryIds = new Set(countries.map((c) => c.id));

/** The N largest bilateral exposures, for rendering as arcs on the globe. */
export function topExposureEdges(yearData: YearSnapshot, limit: number): ExposureEdge[] {
  return yearData.edges
    .filter((e) => countryIds.has(e.creditor) && countryIds.has(e.debtor))
    .slice()
    .sort((a, b) => b.amount - a.amount)
    .slice(0, limit)
    .map((e) => ({ creditor: e.creditor, debtor: e.debtor, amount: e.amount }));
}

export interface BorderRing {
  name: string;
  /** [lng, lat] pairs. */
  points: [number, number][];
}

interface RawBorders {
  countries: { name: string; rings: [number, number][][] }[];
}

export function loadBorders(): BorderRing[] {
  const raw = borders as RawBorders;
  const out: BorderRing[] = [];
  for (const c of raw.countries) {
    for (const ring of c.rings) {
      out.push({ name: c.name, points: ring });
    }
  }
  return out;
}

export function latLngToVector3(lat: number, lng: number, radius: number): [number, number, number] {
  const phi = (90 - lat) * (Math.PI / 180);
  const theta = (lng + 180) * (Math.PI / 180);
  const x = -radius * Math.sin(phi) * Math.cos(theta);
  const z = radius * Math.sin(phi) * Math.sin(theta);
  const y = radius * Math.cos(phi);
  return [x, y, z];
}
