import type { ExposureNetwork } from "./debtrank";
import countryList from "../data/network_snapshot.json";
import borders from "../data/world_borders.json";

export interface CountryNode {
  id: string;
  name: string;
  lat: number;
  lng: number;
}

interface RawCountryList {
  nodes: { id: string; name: string; lat: number | null; lng: number | null }[];
}

// id/name/lat/lng never change across years, so this stays a static bundled
// import; the per-year financials and exposure edges are fetched on demand
// via loadYearData below (see YEARS / the historical scrubber in App.tsx).
export const countries: CountryNode[] = (countryList as RawCountryList).nodes
  .filter((n) => n.lat !== null && n.lng !== null)
  .map((n) => ({ id: n.id, name: n.name, lat: n.lat as number, lng: n.lng as number }));

export const YEARS = Array.from({ length: 21 }, (_, i) => 2005 + i);
export const DEFAULT_YEAR = YEARS[YEARS.length - 1];

export interface ExposureEdge {
  creditor: string;
  debtor: string;
  amount: number;
}

interface YearNode {
  id: string;
  gdp_usd: number | null;
  reserves_usd: number | null;
  external_debt_usd: number | null;
}

export interface YearSnapshot {
  nodes: YearNode[];
  edges: ExposureEdge[];
}

const yearCache = new Map<number, YearSnapshot>();

/** Fetches (and caches) the network snapshot for a given year, generated by
 * data-pipeline/build_snapshot.py --by-year and served statically from
 * public/data/network/{year}.json. */
export async function loadYearData(year: number): Promise<YearSnapshot> {
  const cached = yearCache.get(year);
  if (cached) return cached;
  const res = await fetch(`/data/network/${year}.json`);
  if (!res.ok) throw new Error(`Failed to load network data for ${year}`);
  const data = (await res.json()) as YearSnapshot;
  yearCache.set(year, data);
  return data;
}

// Same equity fallback as model/debtrank_model/cli.py: reserves are the
// natural sovereign loss-absorbing buffer, falling back to a slice of GDP,
// then a floor, so every node has strictly positive equity.
function equityFor(n: YearNode | undefined): number {
  if (n?.reserves_usd) return n.reserves_usd;
  if (n?.gdp_usd) return n.gdp_usd * 0.01;
  return 1e6;
}

export function buildExposureNetwork(yearData: YearSnapshot): ExposureNetwork {
  const nodeIds = countries.map((c) => c.id);
  const index = new Map(nodeIds.map((id, i) => [id, i]));
  const byId = new Map(yearData.nodes.map((n) => [n.id, n]));
  const equity = nodeIds.map((id) => equityFor(byId.get(id)));

  const n = nodeIds.length;
  const exposure: number[][] = Array.from({ length: n }, () => new Array(n).fill(0));
  for (const e of yearData.edges) {
    const i = index.get(e.creditor);
    const j = index.get(e.debtor);
    if (i === undefined || j === undefined) continue;
    exposure[i][j] += e.amount;
  }

  return { nodeIds, exposure, equity };
}

/** Total in + out exposure for a country, used to size its marker. */
export function totalExposure(yearData: YearSnapshot, countryId: string): number {
  let total = 0;
  for (const e of yearData.edges) {
    if (e.creditor === countryId || e.debtor === countryId) total += e.amount;
  }
  return total;
}

const countryIds = new Set(countries.map((c) => c.id));

/** The N largest bilateral exposures, for rendering as arcs on the globe. */
export function topExposureEdges(yearData: YearSnapshot, limit: number): ExposureEdge[] {
  return yearData.edges
    .filter((e) => countryIds.has(e.creditor) && countryIds.has(e.debtor))
    .slice()
    .sort((a, b) => b.amount - a.amount)
    .slice(0, limit)
    .map((e) => ({ creditor: e.creditor, debtor: e.debtor, amount: e.amount }));
}

export interface BorderRing {
  name: string;
  /** [lng, lat] pairs. */
  points: [number, number][];
}

interface RawBorders {
  countries: { name: string; rings: [number, number][][] }[];
}

export function loadBorders(): BorderRing[] {
  const raw = borders as RawBorders;
  const out: BorderRing[] = [];
  for (const c of raw.countries) {
    for (const ring of c.rings) {
      out.push({ name: c.name, points: ring });
    }
  }
  return out;
}

export function latLngToVector3(lat: number, lng: number, radius: number): [number, number, number] {
  const phi = (90 - lat) * (Math.PI / 180);
  const theta = (lng + 180) * (Math.PI / 180);
  const x = -radius * Math.sin(phi) * Math.cos(theta);
  const z = radius * Math.sin(phi) * Math.sin(theta);
  const y = radius * Math.cos(phi);
  return [x, y, z];
}
